image: python:3.7-alpine

stages:
  - pages
  - test_local
  - test
  - codequality
  - commentquality

pages:
  stage: pages
  image: python:3.8
  script:
  - pip install -e .[dev]
  - pip install sphinx_rtd_theme
  - sphinx-build -d _build/doctrees docs/source _build/html
  - mv _build/html public
  artifacts:
        paths:
        - public
  only:
  - master

tests_local:
  stage: test_local
  image: python:3.8
  script:
   - pwd
   - ls
   - pip install -e .[dev]
   - cd tests
   - pytest --durations=10 -m 'local'

tests:
  stage: test
  image: python:3.8
  script:
   - pwd
   - ls
   - pip install -e .[dev]
   - cd tests
   - pytest --durations=10 -m 'not local'

flake8:
  stage: codequality
  image: python:3.8
  allow_failure: true
  script:
    - pip uninstall -y konfuzio_sdk
    - pip install -e .[dev]
    - flake8

docstrings:
  stage: commentquality
  image: python:3.8
  allow_failure: true
  script:
    - pip uninstall -y konfuzio_sdk
    - pip install -e .[dev]
    - cd konfuzio_sdk
    - pydocstyle
